# Sidebar navigation

- label: Linuxサーバーの学習 - 事前準備
  items:
    - label: '必要なソフトウェアの準備'
      link: '/linux_control/software_preparation'
    - label: 'Linuxサーバーへのログイン手順'
      link: '/linux_control/login_procedure'
- label: 'Linuxサーバーの学習 - コマンド操作'
  items:
    - label: 'cd'
      link: '/command/command_control_cd'
    - label: 'ls'
      link: '/command/command_control_ls'
    - label: 'vi'
      link: '/command/command_control_vi'
    - label: 'cat'
      link: '/command/command_control_cat'
    - label: 'less'
      link: '/command/command_control_less'
    - label: 'find'
      link: '/command/command_control_find'
    - label: 'touch'
      link: '/command/command_control_touch'
    - label: 'mkdir'
      link: '/command/command_control_mkdir'
    - label: 'rm'
      link: '/command/command_control_rm'
    - label: 'cp'
      link: '/command/command_control_cp'
    - label: 'mv'
      link: '/command/command_control_mv'
    - label: 'grep'
      link: '/command/command_control_grep'
    - label: 'chmod'
      link: '/command/command_control_chmod'
    - label: 'chown'
      link: '/command/command_control_chown'
    - label: 'chgrp'
      link: '/command/command_control_chgrp'
    - label: 'passwd'
      link: '/command/command_control_passwd'
    - label: 'pwd'
      link: '/command/command_control_pwd'
    - label: 'diff'
      link: '/command/command_control_diff'
    - label: 'clear'
      link: '/command/command_control_clear'
    - label: 'history'
      link: '/command/command_control_history'
    - label: 'top'
      link: '/command/command_control_top'
    - label: 'free'
      link: '/command/command_control_free'
    - label: 'su'
      link: '/command/command_control_su'
    - label: 'sudo'
      link: '/command/command_control_sudo'
    - label: 'exit'
      link: '/command/command_control_exit'
    - label: 'shutdown'
      link: '/command/command_control_shutdown'
- label: 'AWSクラウドプラクティショナー資格学習 - 事前準備'
  items:
    - label: 'アカウント登録'
      link: '/aws_cp/advance_preparation/aws_cp_account_registration'
- label: 'AWSクラウドプラクティショナー資格学習 - クラウドとAWSの概要'
  items:
    - label: '仮想化とは'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_what_is_virtualization'