# Sidebar navigation

- label: Linuxサーバーの学習
  items:
    - label: '必要なソフトウェアの準備'
      link: '/software_preparation'
    - label: 'Linuxサーバーへのログイン手順'
      link: '/login_procedure'
- label: 'コマンド操作の学習'
  items:
    - label: 'cd'
      link: '/command_control_cd'
    - label: 'ls'
      link: '/command_control_ls'
    - label: 'vi'
      link: '/command_control_vi'
    - label: 'cat'
      link: '/command_control_cat'
    - label: 'less'
      link: '/command_control_less'
    - label: 'find'
      link: '/command_control_find'
    - label: 'touch'
      link: '/command_control_touch'
    - label: 'mkdir'
      link: '/command_control_mkdir'
    - label: 'rm'
      link: '/command_control_rm'
    - label: 'cp'
      link: '/command_control_cp'
    - label: 'mv'
      link: '/command_control_mv'
    - label: 'grep'
      link: '/command_control_grep'
    - label: 'chmod'
      link: '/command_control_chmod'
    - label: 'chown'
      link: '/command_control_chown'
    - label: 'chgrp'
      link: '/command_control_chgrp'
    - label: 'passwd'
      link: '/command_control_passwd'
    - label: 'pwd'
      link: '/command_control_pwd'
    - label: 'diff'
      link: '/command_control_diff'
    - label: 'clear'
      link: '/command_control_clear'
    - label: 'history'
      link: '/command_control_history'
    - label: 'top'
      link: '/command_control_top'
    - label: 'free'
      link: '/command_control_free'
    - label: 'su'
      link: '/command_control_su'
    - label: 'sudo'
      link: '/command_control_sudo'
    - label: 'exit'
      link: '/command_control_exit'
    - label: 'shutdown'
      link: '/command_control_shutdown'
- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: 'Test'
  link: '/test'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/rocketseat/gatsby-themes
