# Sidebar navigation

- label: Linuxサーバーの学習 - 事前準備
  items:
    - label: '必要なソフトウェアの準備'
      link: '/linux_control/software_preparation'
    - label: 'Linuxサーバーへのログイン手順'
      link: '/linux_control/login_procedure'
- label: 'Linuxサーバーの学習 - コマンド操作'
  items:
    - label: 'cd'
      link: '/command/command_control_cd'
    - label: 'ls'
      link: '/command/command_control_ls'
    - label: 'vi'
      link: '/command/command_control_vi'
    - label: 'cat'
      link: '/command/command_control_cat'
    - label: 'less'
      link: '/command/command_control_less'
    - label: 'find'
      link: '/command/command_control_find'
    - label: 'touch'
      link: '/command/command_control_touch'
    - label: 'mkdir'
      link: '/command/command_control_mkdir'
    - label: 'rm'
      link: '/command/command_control_rm'
    - label: 'cp'
      link: '/command/command_control_cp'
    - label: 'mv'
      link: '/command/command_control_mv'
    - label: 'grep'
      link: '/command/command_control_grep'
    - label: 'chmod'
      link: '/command/command_control_chmod'
    - label: 'chown'
      link: '/command/command_control_chown'
    - label: 'chgrp'
      link: '/command/command_control_chgrp'
    - label: 'passwd'
      link: '/command/command_control_passwd'
    - label: 'pwd'
      link: '/command/command_control_pwd'
    - label: 'diff'
      link: '/command/command_control_diff'
    - label: 'clear'
      link: '/command/command_control_clear'
    - label: 'history'
      link: '/command/command_control_history'
    - label: 'top'
      link: '/command/command_control_top'
    - label: 'free'
      link: '/command/command_control_free'
    - label: 'su'
      link: '/command/command_control_su'
    - label: 'sudo'
      link: '/command/command_control_sudo'
    - label: 'exit'
      link: '/command/command_control_exit'
    - label: 'shutdown'
      link: '/command/command_control_shutdown'
- label: 'AWSクラウドプラクティショナー資格学習 - 事前準備'
  items:
    - label: 'アカウント登録'
      link: '/aws_cp/advance_preparation/aws_cp_account_registration'
- label: 'AWSクラウドプラクティショナー資格学習 - クラウドとAWSの概要'
  items:
    - label: '仮想化とは'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_what_is_virtualization'
    - label: 'クラウドの基礎'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_cloud_basics'
    - label: 'AWSの意義'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_significance_of_aws'
    - label: 'AWSのグローバルインフラ構成'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_grobal_infra_structure_of_aws'
    - label: 'AWSサービスの全体像と試験範囲'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_aws_overall_picture_and_test_scope'
    - label: 'AWSの活用メリット'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_utilization_benefits'
    - label: 'オンプレミスとAWSクラウドの良し悪し'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_good_and_bad_on-premises_and_aws_cloud'
    - label: 'AWSの操作方法'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_how_to_use_aws'
    - label: 'クラウドとAWS概要にかかる模擬試験'
      link: '/aws_cp/cloud_and_aws_overview/aws_cp_cloud_and_aws_overview_test'
- label: 'AWSクラウドプラクティショナー資格学習 - AWSのコアサービス１'
  items:
    - label: 'サーバーの理解'
      link: '/aws_cp/aws_core_service_1/aws_cp_server_understanding'
    - label: 'EC2の概要'
      link: '/aws_cp/aws_core_service_1/aws_cp_ec2_overview'
    - label: 'AWSでサーバーを構築してみる（ハンズオン）'
      link: '/aws_cp/aws_core_service_1/aws_cp_ec2_hands_on'
    - label: 'Macでの操作'
      link: '/aws_cp/aws_core_service_1/aws_cp_mac_operation'
    - label: 'サーバーの役割の再確認'
      link: '/aws_cp/aws_core_service_1/aws_cp_reconfirm_server_role'
    - label: 'EBSの概要'
      link: '/aws_cp/aws_core_service_1/aws_cp_ebs_overview'
    - label: 'EBSの設定（ハンズオン）'
      link: '/aws_cp/aws_core_service_1/aws_cp_ebs_hands_on'
    - label: 'EC2とEBSに関する模擬試験'
      link: '/aws_cp/aws_core_service_1/aws_cp_ec2_and_ebs_test'
    - label: 'サブネットとサブネットマスク'
      link: '/aws_cp/aws_core_service_1/aws_cp_subnet_and_subnetmask'
    - label: 'VPCの概要'
      link: '/aws_cp/aws_core_service_1/aws_cp_vpc_overview'
    - label: 'VPCによるネットワーク構築（ハンズオン）'
      link: '/aws_cp/aws_core_service_1/aws_cp_vpc_hands_on'
    - label: '通信プロトコルとOSI参照モデル'
      link: '/aws_cp/aws_core_service_1/aws_cp_communication_protocol_and_osi_reference_model'
    - label: 'セキュリティグループとネットワークACL'
      link: '/aws_cp/aws_core_service_1/aws_cp_securitygroup_and_networkacl'
    - label: 'セキュリティグループの活用（ハンズオン）'
      link: '/aws_cp/aws_core_service_1/aws_cp_securitygroup_hands_on'
    - label: 'ネットワークACLの活用（ハンズオン）'
      link: '/aws_cp/aws_core_service_1/aws_cp_networkacl_hands_on'
    - label: 'VPCとトラフィック制御に関する模擬試験'
      link: '/aws_cp/aws_core_service_1/aws_cp_vpc_and_traffic_test'
    - label: 'Route53の概要'
      link: '/aws_cp/aws_core_service_1/aws_cp_route53_overview'
